#! /bin/bash

# Update codebase
git pull
npm install

# Rebuild server
npm run build

# Move logs to log file with timestamp as filename
# mv out.log logs/$(date +%F-%T).log

echo "DONE" 
# Show status
# forever list